# Site wide configuration

title: Balaji Nagaraj Kumar 
locale: en_US
description: Self Portfolio
logo: bio-photo.jpg
search: true
url: http://balajinagarajkumar.me

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name : Balaji Nagaraj Kumar
  avatar: bio-photo.jpg
  email: balaji9300@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: balajikingy 
  github: BalajiNagarajKumar 
  linkedin: balaji-nagaraj-kumar
  flickr: #username
  tumblr: #username
  weibo: #userid
  google:
    plus: balaji9300
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
